# Generated by Django 4.2.5 on 2024-02-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_tbl_cost_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cost_revenue',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
