# Generated by Django 4.2.5 on 2024-02-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_tbl_tax_m'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Organization_Ownership_Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_code', models.CharField(max_length=10)),
                ('transfer_code_verify', models.BooleanField(default=False)),
                ('current_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected'), (3, 'Cancelled')])),
            ],
        ),
    ]
